// use https://github.com/oslllo/svg-fixer if some icons generated with generate-icons command are showing incorectly
export default {
  name: 'custom-icons',
  type: {
    positive: 'icon-mat-check_circle',
    negative: 'icon-mat-warning',
    info: 'icon-mat-info',
    warning: 'icon-mat-priority_high',
  },
  arrow: {
    up: 'icon-mat-arrow_upward',
    right: 'icon-mat-arrow_forward',
    down: 'icon-mat-arrow_downward',
    left: 'icon-mat-arrow_back',
    dropdown: 'icon-mat-arrow_drop_down',
  },
  chevron: {
    left: 'icon-mat-chevron_left',
    right: 'icon-mat-chevron_right',
  },
  colorPicker: {
    spectrum: 'icon-mat-gradient',
    tune: 'icon-mat-tune',
    palette: 'icon-mat-style',
  },
  pullToRefresh: {
    icon: 'icon-mat-refresh',
  },
  carousel: {
    left: 'icon-mat-chevron_left',
    right: 'icon-mat-chevron_right',
    up: 'icon-mat-keyboard_arrow_up',
    down: 'icon-mat-keyboard_arrow_down',
    navigationIcon: 'icon-mat-lens',
  },
  chip: {
    remove: 'icon-mat-cancel',
    selected: 'icon-mat-check',
  },
  datetime: {
    arrowLeft: 'icon-mat-chevron_left',
    arrowRight: 'icon-mat-chevron_right',
    now: 'icon-mat-access_time',
    today: 'icon-mat-today',
  },
  editor: {
    bold: 'icon-mat-format_bold',
    italic: 'icon-mat-format_italic',
    strikethrough: 'icon-mat-strikethrough_s',
    underline: 'icon-mat-format_underlined',
    unorderedList: 'icon-mat-format_list_bulleted',
    orderedList: 'icon-mat-format_list_numbered',
    subscript: 'icon-mat-vertical_align_bottom',
    superscript: 'icon-mat-vertical_align_top',
    hyperlink: 'icon-mat-link',
    toggleFullscreen: 'icon-mat-fullscreen',
    quote: 'icon-mat-format_quote',
    left: 'icon-mat-format_align_left',
    center: 'icon-mat-format_align_center',
    right: 'icon-mat-format_align_right',
    justify: 'icon-mat-format_align_justify',
    print: 'icon-mat-print',
    outdent: 'icon-mat-format_indent_decrease',
    indent: 'icon-mat-format_indent_increase',
    removeFormat: 'icon-mat-format_clear',
    formatting: 'icon-mat-text_format',
    fontSize: 'icon-mat-format_size',
    align: 'icon-mat-format_align_left',
    hr: 'icon-mat-remove',
    undo: 'icon-mat-undo',
    redo: 'icon-mat-redo',
    heading: 'icon-mat-format_size',
    code: 'icon-mat-code',
    size: 'icon-mat-format_size',
    font: 'icon-mat-font_download',
    viewSource: 'icon-mat-code',
  },
  expansionItem: {
    icon: 'icon-mat-keyboard_arrow_down',
    denseIcon: 'icon-mat-arrow_drop_down',
  },
  fab: {
    icon: 'icon-mat-add',
    activeIcon: 'icon-mat-close',
  },
  field: {
    clear: 'icon-mat-cancel',
    error: 'icon-mat-error',
  },
  pagination: {
    first: 'icon-mat-first_page',
    prev: 'icon-mat-keyboard_arrow_left',
    next: 'icon-mat-keyboard_arrow_right',
    last: 'icon-mat-last_page',
  },
  rating: {
    icon: 'icon-mat-grade',
  },
  stepper: {
    done: 'icon-mat-check',
    active: 'icon-mat-edit',
    error: 'icon-mat-warning',
  },
  tabs: {
    left: 'icon-mat-chevron_left',
    right: 'icon-mat-chevron_right',
    up: 'icon-mat-keyboard_arrow_up',
    down: 'icon-mat-keyboard_arrow_down',
  },
  table: {
    arrowUp: 'icon-mat-arrow_upward',
    warning: 'icon-mat-warning',
    firstPage: 'icon-mat-first_page',
    prevPage: 'icon-mat-chevron_left',
    nextPage: 'icon-mat-chevron_right',
    lastPage: 'icon-mat-last_page',
  },
  tree: {
    icon: 'icon-mat-play_arrow',
  },
  uploader: {
    done: 'icon-mat-done',
    clear: 'icon-mat-clear',
    add: 'icon-mat-add_box',
    upload: 'icon-mat-cloud_upload',
    removeQueue: 'icon-mat-clear_all',
    removeUploaded: 'icon-mat-done_all',
  },
};
